/**************************************************************************
 SDLApiClient - GroupShare Web API

 Copyright (C) 2019 Briac Pilpré
 Home page: http://www.omegat.org/
 Support center: http://groups.yahoo.com/group/OmegaT/

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program. If not, see <http://www.gnu.org/licenses/>.
 **************************************************************************/
package net.briac.sdl;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.ResourceBundle;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author briac
 */
public class GroupshareTMWindow extends javax.swing.JFrame {

    private static final String GROUPSHARE_PROPERTIES = "groupshare.properties";
    private static final String GROUPSHARE_SERVER = "groupshare.server";
    private static final String GROUPSHARE_LOGIN = "groupshare.login";
    private static final String GROUPSHARE_PASSWORD = "groupshare.password";

    private static final long serialVersionUID = 7153779047527692921L;

    private static ResourceBundle res = ResourceBundle.getBundle("net.briac.sdl.GroupshareTMWindow");
    Properties defaultProps = new Properties();

    /**
     * Creates new form GroupshareTMWindow
     */
    public GroupshareTMWindow() {
        File propFile = new File(GROUPSHARE_PROPERTIES);
        boolean propLoaded = false;
        if (propFile.exists()) {
            try {
                defaultProps.load(new FileInputStream(propFile));
                propLoaded = true;
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        initComponents();
        setTitle(res.getString("FRAME_TITLE"));
        if (propLoaded) {
            fieldServerAddress.setText(defaultProps.getProperty(GROUPSHARE_SERVER, ""));
            fieldLogin.setText(defaultProps.getProperty(GROUPSHARE_LOGIN, ""));
            fieldPassword.setText(defaultProps.getProperty(GROUPSHARE_PASSWORD, ""));
            fieldSdlppx.grabFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGroupshare = new javax.swing.JPanel();
        labelServerAddress = new javax.swing.JLabel();
        fieldServerAddress = new javax.swing.JTextField();
        labelLogin = new javax.swing.JLabel();
        fieldLogin = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        panelProject = new javax.swing.JPanel();
        labelSdlppx = new javax.swing.JLabel();
        fieldSdlppx = new javax.swing.JTextField();
        buttonBrowse = new javax.swing.JButton();
        buttonFetchTm = new javax.swing.JButton();
        scrollLog = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        buttonSavePrefs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGroupshare.setBorder(javax.swing.BorderFactory.createTitledBorder(res.getString("PANEL_GROUPSHARE"))); // NOI18N

        labelServerAddress.setText(res.getString("SERVER_ADDRESS")); // NOI18N

        labelLogin.setText(res.getString("SERVER_LOGIN")); // NOI18N
        labelLogin.setToolTipText("");

        labelPassword.setText(res.getString("SERVER_PASSWORD")); // NOI18N
        labelPassword.setToolTipText("");

        javax.swing.GroupLayout panelGroupshareLayout = new javax.swing.GroupLayout(panelGroupshare);
        panelGroupshare.setLayout(panelGroupshareLayout);
        panelGroupshareLayout.setHorizontalGroup(panelGroupshareLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGroupshareLayout.createSequentialGroup().addContainerGap().addGroup(panelGroupshareLayout
                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelLogin, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelServerAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGroupshareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldServerAddress)
                                .addComponent(fieldLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fieldPassword))
                        .addContainerGap()));
        panelGroupshareLayout.setVerticalGroup(panelGroupshareLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelGroupshareLayout.createSequentialGroup().addContainerGap()
                        .addGroup(panelGroupshareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelServerAddress).addComponent(fieldServerAddress,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGroupshareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelLogin).addComponent(fieldLogin,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelGroupshareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelPassword).addComponent(fieldPassword,
                                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        panelProject.setBorder(javax.swing.BorderFactory.createTitledBorder(res.getString("PANEL_SDL_PROJECT"))); // NOI18N

        labelSdlppx.setText(res.getString("SDL_PPX_FILE")); // NOI18N

        buttonBrowse.setText(res.getString("BUTTON_BROWSE")); // NOI18N
        buttonBrowse.addActionListener(evt -> buttonBrowseActionPerformed(evt));

        javax.swing.GroupLayout panelProjectLayout = new javax.swing.GroupLayout(panelProject);
        panelProject.setLayout(panelProjectLayout);
        panelProjectLayout
                .setHorizontalGroup(panelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelProjectLayout.createSequentialGroup().addContainerGap()
                                .addComponent(labelSdlppx, javax.swing.GroupLayout.PREFERRED_SIZE, 78,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldSdlppx, javax.swing.GroupLayout.PREFERRED_SIZE, 187,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        panelProjectLayout.setVerticalGroup(panelProjectLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelProjectLayout.createSequentialGroup().addContainerGap()
                        .addGroup(panelProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelSdlppx)
                                .addComponent(fieldSdlppx, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonBrowse))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        buttonFetchTm.setText(res.getString("BUTTON_FETCH_TM")); // NOI18N
        buttonFetchTm.setToolTipText("");
        buttonFetchTm.addActionListener(evt -> buttonFetchTmActionPerformed(evt));

        logArea.setColumns(20);
        logArea.setRows(5);
        scrollLog.setViewportView(logArea);

        buttonSavePrefs.setText(res.getString("SAVE_PREFS")); // NOI18N
        buttonSavePrefs.addActionListener(evt -> buttonSavePrefsActionPerformed(evt));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(scrollLog)
                        .addComponent(panelGroupshare, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelProject, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(buttonSavePrefs, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonFetchTm, javax.swing.GroupLayout.PREFERRED_SIZE, 90,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(panelGroupshare, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelProject, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(buttonFetchTm).addComponent(buttonSavePrefs))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollLog, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBrowseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonBrowseActionPerformed
        File currentDirectory = new File(fieldSdlppx.getText());
        JFileChooser fc;
        if (currentDirectory.exists()) {
            fc = new JFileChooser(currentDirectory);
        } else {
            fc = new JFileChooser();
        }

        fc.setFileFilter(new FileFilter() {

            @Override
            public String getDescription() {
                return "SDLPPX Files";
            }

            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".sdlppx");
            }
        });

        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            fieldSdlppx.setText(file.getAbsolutePath());
        }
    }// GEN-LAST:event_buttonBrowseActionPerformed

    private void buttonFetchTmActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonFetchTmActionPerformed
        logArea.setText("");
        try {
            GroupshareTMClient gtc = new GroupshareTMClient();
            gtc.setLogArea(logArea);
            gtc.downloadTM(fieldServerAddress.getText(), fieldLogin.getText(), new String(fieldPassword.getPassword()),
                    fieldSdlppx.getText());
        } catch (Exception ex) {
            logArea.append(ex.getMessage());
        }
    }// GEN-LAST:event_buttonFetchTmActionPerformed

    private void buttonSavePrefsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSavePrefsActionPerformed
        defaultProps.setProperty(GROUPSHARE_SERVER, fieldServerAddress.getText());
        defaultProps.setProperty(GROUPSHARE_LOGIN, fieldLogin.getText());
        defaultProps.setProperty(GROUPSHARE_PASSWORD, new String(fieldPassword.getPassword()));

        try {
            FileOutputStream fos = new FileOutputStream(new File(GROUPSHARE_PROPERTIES));
            defaultProps.store(fos, "Groupshare TM Client");
            logArea.append("Preferences saved.");
        } catch (IOException e) {
            logArea.append(e.getMessage());
        }
    }// GEN-LAST:event_buttonSavePrefsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBrowse;
    private javax.swing.JButton buttonFetchTm;
    private javax.swing.JButton buttonSavePrefs;
    protected javax.swing.JTextField fieldLogin;
    protected javax.swing.JPasswordField fieldPassword;
    protected javax.swing.JTextField fieldSdlppx;
    protected javax.swing.JTextField fieldServerAddress;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelSdlppx;
    private javax.swing.JLabel labelServerAddress;
    private javax.swing.JTextArea logArea;
    private javax.swing.JPanel panelGroupshare;
    private javax.swing.JPanel panelProject;
    private javax.swing.JScrollPane scrollLog;
    // End of variables declaration//GEN-END:variables
}
